# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ko-KR
reviews:
  profile: assertive
  high_level_summary_instructions: |-
    ### 주요 지침 요약
    - API 명세서 기준으로 요청/응답 구조, 필드명, 상태 코드가 정확히 반영되었는지 검토
    - 기능 변경 여부 및 기존 기능에 대한 영향 범위 확인
    - 인증/인가 로직과 예외 처리 흐름의 일관성 검토
    - 트랜잭션 경계 및 Optional 사용 적절성 검토
    - 팀 코드 컨벤션 및 메서드 명명 규칙 준수 여부 확인
